replicaCount: 20
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: azure-vote.tietoevry.site
      paths:
        - "/"
  tls:
    - secretName: azure-vote-tietoevry-tls
      hosts:
        - azure-vote.tietoevry.site
